# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import urgences_pb2 as urgences__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in urgences_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UrgenceServiceStub(object):
    """--- SERVICE ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignalerUrgence = channel.unary_unary(
                '/urgences.UrgenceService/SignalerUrgence',
                request_serializer=urgences__pb2.UrgenceRequest.SerializeToString,
                response_deserializer=urgences__pb2.UrgenceResponse.FromString,
                _registered_method=True)
        self.SuivreIntervention = channel.unary_stream(
                '/urgences.UrgenceService/SuivreIntervention',
                request_serializer=urgences__pb2.SuiviRequest.SerializeToString,
                response_deserializer=urgences__pb2.SuiviUpdate.FromString,
                _registered_method=True)
        self.HistoriqueUrgences = channel.unary_unary(
                '/urgences.UrgenceService/HistoriqueUrgences',
                request_serializer=urgences__pb2.HistoriqueRequest.SerializeToString,
                response_deserializer=urgences__pb2.HistoriqueResponse.FromString,
                _registered_method=True)


class UrgenceServiceServicer(object):
    """--- SERVICE ---
    """

    def SignalerUrgence(self, request, context):
        """1. Signaler une urgence (Unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuivreIntervention(self, request, context):
        """2. Suivre une intervention en temps réel (Server Streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HistoriqueUrgences(self, request, context):
        """3. Récupérer l'historique (Unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UrgenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignalerUrgence': grpc.unary_unary_rpc_method_handler(
                    servicer.SignalerUrgence,
                    request_deserializer=urgences__pb2.UrgenceRequest.FromString,
                    response_serializer=urgences__pb2.UrgenceResponse.SerializeToString,
            ),
            'SuivreIntervention': grpc.unary_stream_rpc_method_handler(
                    servicer.SuivreIntervention,
                    request_deserializer=urgences__pb2.SuiviRequest.FromString,
                    response_serializer=urgences__pb2.SuiviUpdate.SerializeToString,
            ),
            'HistoriqueUrgences': grpc.unary_unary_rpc_method_handler(
                    servicer.HistoriqueUrgences,
                    request_deserializer=urgences__pb2.HistoriqueRequest.FromString,
                    response_serializer=urgences__pb2.HistoriqueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'urgences.UrgenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('urgences.UrgenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UrgenceService(object):
    """--- SERVICE ---
    """

    @staticmethod
    def SignalerUrgence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/urgences.UrgenceService/SignalerUrgence',
            urgences__pb2.UrgenceRequest.SerializeToString,
            urgences__pb2.UrgenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuivreIntervention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/urgences.UrgenceService/SuivreIntervention',
            urgences__pb2.SuiviRequest.SerializeToString,
            urgences__pb2.SuiviUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HistoriqueUrgences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/urgences.UrgenceService/HistoriqueUrgences',
            urgences__pb2.HistoriqueRequest.SerializeToString,
            urgences__pb2.HistoriqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
