# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: urgences.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'urgences.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eurgences.proto\x12\x08urgences\"2\n\x0b\x43oordonnees\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"{\n\x0eUrgenceRequest\x12+\n\x0ctype_urgence\x18\x01 \x01(\x0e\x32\x15.urgences.TypeUrgence\x12\'\n\x08position\x18\x02 \x01(\x0b\x32\x15.urgences.Coordonnees\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"[\n\x0fUrgenceResponse\x12\x17\n\x0fid_intervention\x18\x01 \x01(\t\x12\x17\n\x0fprise_en_compte\x18\x02 \x01(\x08\x12\x16\n\x0emessage_status\x18\x03 \x01(\t\"\'\n\x0cSuiviRequest\x12\x17\n\x0fid_intervention\x18\x01 \x01(\t\"y\n\x0bSuiviUpdate\x12\x37\n\x18position_actuelle_equipe\x18\x01 \x01(\x0b\x32\x15.urgences.Coordonnees\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\x12\x19\n\x11temps_restant_min\x18\x03 \x01(\x05\"\x13\n\x11HistoriqueRequest\"H\n\x12HistoriqueResponse\x12\x32\n\x10urgences_passees\x18\x01 \x03(\x0b\x32\x18.urgences.UrgenceRequest*b\n\x0bTypeUrgence\x12\x0b\n\x07INCONNU\x10\x00\x12\x12\n\x0e\x41\x43\x43IDENT_ROUTE\x10\x01\x12\x0c\n\x08INCENDIE\x10\x02\x12\x15\n\x11MALAISE_CARDIAQUE\x10\x03\x12\r\n\tFUITE_GAZ\x10\x04\x32\xf0\x01\n\x0eUrgenceService\x12\x46\n\x0fSignalerUrgence\x12\x18.urgences.UrgenceRequest\x1a\x19.urgences.UrgenceResponse\x12\x45\n\x12SuivreIntervention\x12\x16.urgences.SuiviRequest\x1a\x15.urgences.SuiviUpdate0\x01\x12O\n\x12HistoriqueUrgences\x12\x1b.urgences.HistoriqueRequest\x1a\x1c.urgences.HistoriqueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'urgences_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TYPEURGENCE']._serialized_start=557
  _globals['_TYPEURGENCE']._serialized_end=655
  _globals['_COORDONNEES']._serialized_start=28
  _globals['_COORDONNEES']._serialized_end=78
  _globals['_URGENCEREQUEST']._serialized_start=80
  _globals['_URGENCEREQUEST']._serialized_end=203
  _globals['_URGENCERESPONSE']._serialized_start=205
  _globals['_URGENCERESPONSE']._serialized_end=296
  _globals['_SUIVIREQUEST']._serialized_start=298
  _globals['_SUIVIREQUEST']._serialized_end=337
  _globals['_SUIVIUPDATE']._serialized_start=339
  _globals['_SUIVIUPDATE']._serialized_end=460
  _globals['_HISTORIQUEREQUEST']._serialized_start=462
  _globals['_HISTORIQUEREQUEST']._serialized_end=481
  _globals['_HISTORIQUERESPONSE']._serialized_start=483
  _globals['_HISTORIQUERESPONSE']._serialized_end=555
  _globals['_URGENCESERVICE']._serialized_start=658
  _globals['_URGENCESERVICE']._serialized_end=898
# @@protoc_insertion_point(module_scope)
